server:
  port: 8848
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  datasource:
    username: sys_em
    password: dkeujgjgb!2^@dTt
    url: jdbc:mysql://rm-2zeill7d837f111yi1o.mysql.rds.aliyuncs.com:3306/sys_em
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456
  redis:
    port: 6379
    host: localhost
    password: 123456


logging:
  file:
    name: log/log.txt
  level:
    cn.mrcsh.Mapper: info


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/*.xml